--liquibase formatted sql
--changeset elorak:create-rback

DROP TABLE IF EXISTS SEC_PERMISSIONS;

CREATE TABLE IF NOT EXISTS SEC_PERMISSIONS (
  PERMISSIONNAME VARCHAR(50) PRIMARY KEY NOT NULL,
  DESCRIPTION VARCHAR(300),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR(50)
);

DROP TABLE IF EXISTS SEC_ROLES;

CREATE TABLE IF NOT EXISTS SEC_ROLES (
  ROLENAME VARCHAR(50) PRIMARY KEY NOT NULL,
  DESCRIPTION VARCHAR(300),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR(50)
);

DROP TABLE IF EXISTS SEC_USERS;

CREATE TABLE IF NOT EXISTS SEC_USERS (
  USERNAME VARCHAR(50) PRIMARY KEY NOT NULL,
  PASSWORD VARCHAR(256) NOT NULL,
  DESCRIPTION VARCHAR(300),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR(50)
);

DROP TABLE IF EXISTS SEC_USERS_ROLES;

CREATE TABLE IF NOT EXISTS SEC_USERS_ROLES (
  USERNAME VARCHAR(50) NOT NULL,
  ROLENAME VARCHAR(50) NOT NULL,
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR(50),
  PRIMARY KEY (USERNAME, ROLENAME),
  FOREIGN KEY (USERNAME) REFERENCES SEC_USERS (USERNAME),
  FOREIGN KEY (ROLENAME) REFERENCES SEC_ROLES (ROLENAME)
);

DROP TABLE IF EXISTS SEC_ROLES_PERMISSIONS;

CREATE TABLE IF NOT EXISTS SEC_ROLES_PERMISSIONS (
  ROLENAME VARCHAR(50) NOT NULL,
  PERMISSIONNAME VARCHAR(50) NOT NULL,
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR(50),
  PRIMARY KEY (ROLENAME, PERMISSIONNAME),
  FOREIGN KEY (ROLENAME) REFERENCES SEC_ROLES (ROLENAME),
  FOREIGN KEY (PERMISSIONNAME) REFERENCES SEC_PERMISSIONS (PERMISSIONNAME)
);