--liquibase formatted sql
--changeset elorak:create-fee_types

DROP TABLE IF EXISTS T_FEE_TYPES;

CREATE TABLE IF NOT EXISTS T_FEE_TYPES (
  ID_FEE_TYPE INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  FEE_NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(300),
  AMOUNT NUMERIC(10,3) NOT NULL,
  INITIAL_MONTH INTEGER NOT NULL,
  PERIODICITY INTEGER NOT NULL DEFAULT 12,
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR(50)
);

--rollback DROP TABLE T_FEE_TYPES;
