--liquibase formatted sql
--changeset elorak:create-memberships

DROP TABLE IF EXISTS T_MEMBERSHIPS;

CREATE TABLE IF NOT EXISTS T_MEMBERSHIPS (
  ID_MEMBERSHIP INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ID_FEE_TYPE INTEGER NOT NULL,
  MEMBERSHIP_NAME VARCHAR(50) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
  IBAN VARCHAR(4),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR(50),
  CONSTRAINT FK_FEE_TYPE FOREIGN KEY (ID_FEE_TYPE) REFERENCES T_FEE_TYPES(ID_FEE_TYPE) ON DELETE RESTRICT
);

--rollback DROP TABLE T_MEMBERSHIPS;
