--liquibase formatted sql
--changeset elorak:create-member_types

DROP TABLE IF EXISTS T_MEMBER_TYPES;

CREATE TABLE IF NOT EXISTS T_MEMBER_TYPES (
  ID_MEMBER_TYPE INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  LABEL VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(200),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR(50)
);

-- SQLite no soporta COMMENT ON TABLE ni COLUMN, se omiten.

--rollback DROP TABLE T_MEMBER_TYPES;