--liquibase formatted sql
--changeset elorak:create-members

DROP TABLE IF EXISTS T_MEMBERS;

CREATE TABLE IF NOT EXISTS T_MEMBERS (
  ID_MEMBER INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ID_MEMBERSHIP INTEGER,
  MEMBER_NUMBER INTEGER NOT NULL,
  DNI VARCHAR(15),
  NAME VARCHAR(100) NOT NULL,
  SURNAME1 VARCHAR(100) NOT NULL,
  SURNAME2 VARCHAR(100),
  BIRTH_DATE DATE NOT NULL,
  PHONE1 NUMERIC(9,0),
  PHONE2 NUMERIC(9,0),
  EMAIL VARCHAR(100),
  ADDRESS VARCHAR(300),
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR(50),
  CONSTRAINT MEMBER_NUMBER_UNIQUE UNIQUE (MEMBER_NUMBER),
  CONSTRAINT FK_MEMBERSHIPS FOREIGN KEY (ID_MEMBERSHIP) REFERENCES T_MEMBERSHIPS(ID_MEMBERSHIP) ON DELETE RESTRICT
);

-- SQLite no soporta COMMENT ON, por eso se eliminan esos comandos.

--rollback DROP TABLE T_MEMBERS;
