server:
  port: 8081
  servlet:
    context-path: /bazkide
logging:
  level:
    org.springframework: ERROR
    eus.euskolorak.bazkide: ERROR
spring:
  application:
    name: bazkide
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}
  messages:
    basename: "i18n.messages"
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    url: jdbc:sqlite:database.sqlite?foreign_keys=on
    driver-class-name: $org.sqlite.JDBC
    username: sa
    password:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    jpa:
      database-platform: org.hibernate.community.dialect.SQLiteDialect
      hibernate:
        ddl-auto: validate
      show-sql: false
      generate-statistics: false
      properties:
        hibernate:
          format_sql: false
          use_sql_comments: false
  resources:
    static-locations: classpath:/static/
    cache:
      period: 0
